#!/usr/bin/env bash
# Installs nginx web server & Redirection
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html

# The Redirection 301 Moved Permanently

replacement_str="server_name _;\n\trewrite ^\/redirect_me https:\/\/google.com 301;"
sudo sed -i "s/server_name _;/$replacement_str/" /etc/nginx/sites-enabled/default

sudo nginx -t
sudo service nginx restart
