#!/usr/bin/env bash
# update the packages & Installs nginx web server

sudo apt-get update
sudo apt-get install -y nginx

# The index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# The Redirection 301 Moved Permanently
replacement_str="server_name _;\n\trewrite ^\/redirect_me https:\/\/google.com permanent;"
sudo sed -i "s/server_name _;/$replacement_str/" /etc/nginx/sites-enabled/default

# Customized 404 Error message
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
replacement_str="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$replacement_str/" /etc/nginx/sites-enabled/default

# http response header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# check for syntax errors & restart
sudo nginx -t
sudo service nginx restart
