#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it.

USER="root"
PASSCODE="$1"
DATE=$(date +%d-%m-%Y)

mysqldump -u$USER -p$PASSCODE --all-databases > backup.sql
tar -cvzf $DATE.tar.gz backup.sql
