#!/usr/bin/env bash
# Function to remove the PID file and terminate the script

echo $$ > "/var/run/myscript.pid"
cleanup_and_exit()
{
    echo 'I hate the kill command'
    rm -f "/var/run/myscript.pid"
    exit
}
trap "echo 'Y U no love me?!'" SIGINT
trap 'cleanup_and_exit' SIGQUIT SIGTERM

while ((1)); do
    echo "To infinity and beyond"
    sleep 1
done
