#!/usr/bin/env bash
# displays the content of the file /etc/passwd.

passwd_file="/etc/passwd"
if [ -e "$passwd_file" ]; then
    while IFS= read -r LINE; do
	echo "$LINE" | cut -f 1,3,6 -d ':'
    done < "$passwd_file"
fi
