#!/usr/bin/env bash
# displays the content of the file /etc/passwd, using the while loop + IFS.

passwd_file="/etc/passwd"

while IFS=":" read -r user _ uid gid _ home shell; do
    echo -e "The user $user is part of the $gid gang, lives in $home, and rides"\
	 "$shell.\n$uid's place is protected by the passcode $user, more info"\
	 " about the user here: $uid $user"
done < "$passwd_file"
