#!/usr/bin/env bash
# displays the content of the file /etc/passwd, using the while loop + IFS.

passwd_file="/etc/passwd"

while IFS=":" read -r user passwd uid gid info home shell; do
    echo "The user $user is part of the $uid gang, lives in $home and rides $shell."
    echo "$uid's place is protected by the passcode $passwd, more info about the user here: $uid $info"
done < "$passwd_file"
