#!/usr/bin/env bash
# Parses Apache log access files and groups visitors by IP and HTTP status code.

log_file="apache-access.log"
awk '{ count[$1 " " $9]++ } END { for (key in count) print count[key], key }' "$log_file" | sort -nr
