#!/usr/bin/env bash
# Parses Apache log access files and groups visitors by IP and HTTP status code.

log_file="apache-access.log"
awk '{print $1, $9}' $log_file | sort | uniq -c | sort -nr | awk '{print $1, $2, $3}'
