#!/usr/bin/env bash
# displays "Best School" 10 times and "Hi" before the last one.

n=1
while [ $n -le 10 ]
do
    echo "Best School"
    if [ $n -eq 9 ]
    then
	echo "Hi"
    fi
    n=$(( n + 1 ))
done
