#!/usr/bin/env bash
# Iterates 10 times and displays:"bad luck" for the 4th,"good luck" for the 8th,
# and "Best School" for the other loop iterations

n=1

while [ $n -le 10 ]
do
    if [ $n -eq 4 ]
    then
	echo "bad luck"
    elif [ $n -eq 8 ]
    then
	echo "good luck"
    else
	echo "Best School"
    fi
    n=$(( n + 1 ))
done
