#!/usr/bin/env bash
# Displays numbers from 1 to 20 except for 4, 9 and 17 writes "bad luck from"
# followed by the country believing the number unlucky.

n=1

while [ $n -le 20 ]
do
    echo $n
    case $n in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
	*)
	    ;;
    esac
    n=$(( n + 1 ))
done
