#!/usr/bin/env bash
# displays  information about the "school" file.

FILE=school
if test -e "$FILE"; then
    echo 'school file exists'
    if test -s "$FILE"; then
	echo $FILE 'file is not empty'
    else
	echo 'school file is empty'
    fi
    if test -f "$FILE"; then
	echo $FILE 'is a regular file'
    fi
else
    echo $FILE 'file does not exist'
fi
