#!/usr/bin/env bash
# Install the ufw firewall and setup a few rules on web-01

# Install ufw
sudo apt install ufw

# Deny all incoming traffic except TCP port (22/443/80)
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Allow all outgoing traffic
sudo ufw default allow outgoing

# enable ufw and check the status
sudo ufw enable
sudo ufw status verbose
