#!/usr/bin/env bash
# Update the /etc/hosts file to modify DNS resolutions

cp /etc/hosts ~/hosts.new
echo "127.0.0.2localhost" > ~/hosts.new
echo "8.8.8.8facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
