#!/usr/bin/env bash
#Fixes a container so that Nginx is running as the nginx user.

systemctl stop nginx

sed -i 's/user  nginx;/user nginx nginx;/' /etc/nginx/nginx.conf

sed -i "s/80/8080/g" /etc/nginx/sites-available/default

systemctl start nginx
