#!/usr/bin/env bash
#Fixes a container so that Nginx is running as the nginx user.
service nginx stop
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod u=rw,go=r /etc/nginx/nginx.conf
service nginx start
